{{- if eq (include "cibseven.h2DatabaseIsUsed" .) "true" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cibseven.fullname" . }}-database-h2
  labels:
    {{- include "cibseven.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
{{- end }}
