{{- if .Values.webclient.applicationYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cibseven.fullname" . }}-webclient-config
  labels:
    {{- include "cibseven.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- tpl .Values.webclient.applicationYaml . | nindent 4 }}
{{- end }}
